spring:
  profiles: default
  application:
    name: sccService
server:
  port: 810
girl:
  name: hgl
  age: 36
---
spring:
  profiles: dev
  application:
    name: sccService
server:
  port: 820
girl:
  name: hgl
  age: 19
---
spring:
  profiles: refresh
  application:
    name: refreshService
server:
  port: 8022
girl:
  name: 田艳
  age: 32