spring:
  profiles: default
  application:
    name: sccService
server:
  port: 810
girl:
  name: hgl
  age: 36
---
spring:
  profiles: dev
  application:
    name: sccService
server:
  port: 820
girl:
  name: hg5l
  age: 185
---
spring:
  profiles: refresh
  application:
    name: refreshService
server:
  port: 8022
girl:
  name: 田卓5智
  age: 158
---
spring:
  profiles: test
  application:
    name: sccService
server:
  port: 830
girl:
  name: hgl
  age: 36