spring:
  profiles: default
  application:
    name: userService
server:
  port: 81
girl:
  name: hgl
  age: 36
---
spring:
  profiles: dev
  application:
    name: userService
server:
  port: 82
girl:
  name: hgl
  age: 36
---
spring:
  profiles: test
  application:
    name: userService
server:
  port: 83
girl:
  name: hgl
  age: 36
---
spring:
  profiles: local
  application:
    name: userService
server:
  port: 84
girl:
  name: hgl
  age: 36
---
spring:
  profiles: db1
  application:
    name: userService
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.66:3307/microcloud01?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: root
    password: '{cipher}AQCC4EeX06teaIWhNfZ1hkDWcuUmcQ/qhJbanCqNRhN9i5ugUxGfPIIcudDwvMDua3L+DUJIU6MmRres/bImkGbL4e5MNE4AaMaLhLFiSZGyTWrHJ93GeHPAnpjbjVcn8sXHAAhn8vptoIxVzU/4ww7gtYqFPGKOnN0Pq7BsV94i40bjAEilG9hyxsU64QuLq1n41xXXjuKIcFKGbZHnBXncFh5LtC8KTbnTzU1sAHL28BLav38LEQD8+5yEA7rzx81o+7m5hUbz2OIcMlil33MJ7VCHOcTAsN8tNCru+/xXJTlA7wE3qg/nmN+stL0x6LqU4PaKkTVcQDcgmSOjv2huQerAziUkMw7ry7xQhRsOPIFZ07g+xxxkEWX+aCriLRw='
server:
  port: 990
girl:
  name: hgl
  age: 36
---
spring:
  profiles: db2
  application:
    name: userService
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.66:3307/microcloud01?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: root
    password: '{cipher}AQCC4EeX06teaIWhNfZ1hkDWcuUmcQ/qhJbanCqNRhN9i5ugUxGfPIIcudDwvMDua3L+DUJIU6MmRres/bImkGbL4e5MNE4AaMaLhLFiSZGyTWrHJ93GeHPAnpjbjVcn8sXHAAhn8vptoIxVzU/4ww7gtYqFPGKOnN0Pq7BsV94i40bjAEilG9hyxsU64QuLq1n41xXXjuKIcFKGbZHnBXncFh5LtC8KTbnTzU1sAHL28BLav38LEQD8+5yEA7rzx81o+7m5hUbz2OIcMlil33MJ7VCHOcTAsN8tNCru+/xXJTlA7wE3qg/nmN+stL0x6LqU4PaKkTVcQDcgmSOjv2huQerAziUkMw7ry7xQhRsOPIFZ07g+xxxkEWX+aCriLRw='
server:
  port: 991
girl:
  name: 田应平
  age: 34
---
spring:
  profiles: uat
  application:
    name: userService
server:
  port: '{cipher}AQBLzrHCh5YGxzxhMFHyVjUNuSaYyBhusuuU9kN8BLZFsiR2sI33x+vXmgYviP0mlFifdCGdfdKxl3NWMVfbiELgb6bQOb2aE5Fq1MUesVvy4vbG4DTywMEjnHOwbkgf1C98Zbb6Uz3rtA9HWRrDZMBekOYkWtG6K+UtokkVAbfMgQDI2GG0/iGj8NU3kdcsoYoNcia3zmdCO2jklbuFHGdQao1muT9wk7OqC9U2rvT3wYuEu0Gs/YmBJqn+j7uZQMrrWVl1LWQEXKfsaJsL5/uq3chAY0L7oNvdejQtcX0DB3m9h37Bjq7/0xtiW9leJh97PHEVhKgU5hc355JW2wlsEg2Qt/FRyE3H1Mq5GeZOqwkDfY3/8me91eTGZqCqBIM='
girl:
  name: hgl
  age: 36