spring:
  profiles: default
  application:
    name: userService
server:
  port: 81
---
spring:
  profiles: dev
  application:
    name: userService
server:
  port: 82
---
spring:
  profiles: test
  application:
    name: userService
server:
  port: 83
---
spring:
  profiles: local
  application:
    name: userService
server:
  port: 84
---
spring:
  profiles: db1
  application:
    name: userService
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.66:3307/microcloud01?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: root
    password: rootFwtai
server:
  port: 990
---
spring:
  profiles: db2
  application:
    name: userService
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.66:3307/microcloud03?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: root
    password: rootFwtai
server:
  port: 991
---
spring:
  profiles: uat
  application:
    name: userService
server:
  port: '{cipher}AQBLzrHCh5YGxzxhMFHyVjUNuSaYyBhusuuU9kN8BLZFsiR2sI33x+vXmgYviP0mlFifdCGdfdKxl3NWMVfbiELgb6bQOb2aE5Fq1MUesVvy4vbG4DTywMEjnHOwbkgf1C98Zbb6Uz3rtA9HWRrDZMBekOYkWtG6K+UtokkVAbfMgQDI2GG0/iGj8NU3kdcsoYoNcia3zmdCO2jklbuFHGdQao1muT9wk7OqC9U2rvT3wYuEu0Gs/YmBJqn+j7uZQMrrWVl1LWQEXKfsaJsL5/uq3chAY0L7oNvdejQtcX0DB3m9h37Bjq7/0xtiW9leJh97PHEVhKgU5hc355JW2wlsEg2Qt/FRyE3H1Mq5GeZOqwkDfY3/8me91eTGZqCqBIM='